version: "3.7"

services:
  coredns:
    image: coredns/coredns
    command: -conf Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "9153:9153/tcp"
    volumes:
    - ./coredns:/data:ro
